adminUser:
  password: vault:dconde-cjxd1110/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dconde@cloudbees.com
  token: vault:dconde-cjxd1110/pipelineUser:token
  username: daveconde
prow:
  hmacToken: vault:dconde-cjxd1110/prow:hmacToken
